import { IInventoryItem } from '../../components/atoms/InventoryItems';

export const exampleInventoryItems: IInventoryItem[] = [
	{
		id: '1',
		dgId: 1,
		itemName: 'Czajnik bezprzewodowy z krytą grzałką 1,7 l',
		owner: 'RET',
		status: 50,
		inventoryNumber: 'RET/1/2021',
		quantity: 1,
		unitMeasure: 'szt.',
	},
	{
		id: '2',
		dgId: 2,
		itemName: 'Akumulatorowa szlifierka kątowa 115mm, 18V, 2 x AKU. 5.0Ah L',
		owner: 'RET',
		status: 50,
		inventoryNumber: 'RET/2/2021',
	},
	{
		id: '3',
		dgId: 3,
		itemName: 'Torba do notebooka',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/1/2021',
	},
	{
		id: '4',
		dgId: 4,
		itemName: 'Tester banknotowy',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/2/2021',
	},
	{
		id: '5',
		dgId: 5,
		itemName: 'Telefon komórkowy MAXCOM MM918',
		owner: 'REA',
		status: 80,
		inventoryNumber: 'REA/3/2021',
	},
	{
		id: '6',
		dgId: 6,
		itemName: 'Telefon komórkowy NOKIA',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/4/2021',
	},
	{
		id: '7',
		dgId: 7,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/5/2021',
	},
	{
		id: '8',
		dgId: 8,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/6/2021',
	},
	{
		id: '9',
		dgId: 9,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/7/2021',
	},
	{
		id: '10',
		dgId: 10,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/8/2021',
	},
	{
		id: '11',
		dgId: 11,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/9/2021',
	},
	{
		id: '12',
		dgId: 12,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/10/2021',
	},
	{
		id: '13',
		dgId: 13,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/11/2021',
	},
	{
		id: '14',
		dgId: 14,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/12/2021',
	},
	{
		id: '15',
		dgId: 15,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/13/2021',
	},
	{
		id: '16',
		dgId: 16,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/14/2021',
	},
	{
		id: '17',
		dgId: 17,
		itemName: 'Telefon komórkowy SAMSUNG',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/15/2021',
	},
	{
		id: '18',
		dgId: 18,
		itemName: 'Telefon komórkowy SAGEM',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/16/2021',
	},
	{
		id: '19',
		dgId: 19,
		itemName: 'Telefon komórkowy SIEMENS',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/17/2021',
	},
	{
		id: '20',
		dgId: 20,
		itemName: 'Telefon komórkowy MOTOROLA',
		owner: 'REA',
		status: 50,
		inventoryNumber: 'REA/18/2021',
	},
];
